# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2
import permission_pb2 as permission__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07service\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x10permission.proto\"\xe3\x02\n\x19GenerateVivoxTokenRequest\x12\x43\n\x04type\x18\x01 \x01(\x0e\x32&.service.GenerateVivoxTokenRequestTypeB\r\x92\x41\n2\x08Required\x12\x1f\n\x08username\x18\x02 \x01(\tB\r\x92\x41\n2\x08Required\x12/\n\tchannelId\x18\x03 \x01(\tB\x1c\x92\x41\x19\x32\x17Required if type = join\x12`\n\x0b\x63hannelType\x18\x04 \x01(\x0e\x32-.service.GenerateVivoxTokenRequestChannelTypeB\x1c\x92\x41\x19\x32\x17Required if type = join\x12\x34\n\x0etargetUsername\x18\x05 \x01(\tB\x1c\x92\x41\x19\x32\x17Required if type = kick:\x17\x92\x41\x14\n\x12\xd2\x01\x04type\xd2\x01\x08username\">\n\x1aGenerateVivoxTokenResponse\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x01 \x01(\t\x12\x0b\n\x03uri\x18\x02 \x01(\t*z\n\x1dGenerateVivoxTokenRequestType\x12*\n&generatevivoxtokenrequest_type_unknown\x10\x00\x12\t\n\x05login\x10\x01\x12\x08\n\x04join\x10\x02\x12\x0e\n\njoin_muted\x10\x03\x12\x08\n\x04kick\x10\x04*\x86\x01\n$GenerateVivoxTokenRequestChannelType\x12\x31\n-generatevivoxtokenrequest_channeltype_unknown\x10\x00\x12\x08\n\x04\x65\x63ho\x10\x01\x12\x0e\n\npositional\x10\x02\x12\x11\n\rnonpositional\x10\x03\x32\xa6\x01\n\x07Service\x12\x9a\x01\n\x12GenerateVivoxToken\x12\".service.GenerateVivoxTokenRequest\x1a#.service.GenerateVivoxTokenResponse\";\x82\xd3\xe4\x93\x02\x0e\"\t/v1/token:\x01*\x92\x41$\x12\x14Generate Vivox tokenb\x0c\n\n\n\x06\x42\x65\x61rer\x12\x00\x42\xbf\x01\n%net.accelbyte.extend.serviceextensionP\x01Z%accelbyte.net/extend/serviceextension\xaa\x02!AccelByte.Extend.ServiceExtension\x92\x41H\x12\x1b\n\x14Vivox Authentication2\x03\x31.0\"\x08/serviceZ\x1f\n\x1d\n\x06\x42\x65\x61rer\x12\x13\x08\x02\x1a\rAuthorization \x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n%net.accelbyte.extend.serviceextensionP\001Z%accelbyte.net/extend/serviceextension\252\002!AccelByte.Extend.ServiceExtension\222AH\022\033\n\024Vivox Authentication2\0031.0\"\010/serviceZ\037\n\035\n\006Bearer\022\023\010\002\032\rAuthorization \002'
  _GENERATEVIVOXTOKENREQUEST.fields_by_name['type']._options = None
  _GENERATEVIVOXTOKENREQUEST.fields_by_name['type']._serialized_options = b'\222A\n2\010Required'
  _GENERATEVIVOXTOKENREQUEST.fields_by_name['username']._options = None
  _GENERATEVIVOXTOKENREQUEST.fields_by_name['username']._serialized_options = b'\222A\n2\010Required'
  _GENERATEVIVOXTOKENREQUEST.fields_by_name['channelId']._options = None
  _GENERATEVIVOXTOKENREQUEST.fields_by_name['channelId']._serialized_options = b'\222A\0312\027Required if type = join'
  _GENERATEVIVOXTOKENREQUEST.fields_by_name['channelType']._options = None
  _GENERATEVIVOXTOKENREQUEST.fields_by_name['channelType']._serialized_options = b'\222A\0312\027Required if type = join'
  _GENERATEVIVOXTOKENREQUEST.fields_by_name['targetUsername']._options = None
  _GENERATEVIVOXTOKENREQUEST.fields_by_name['targetUsername']._serialized_options = b'\222A\0312\027Required if type = kick'
  _GENERATEVIVOXTOKENREQUEST._options = None
  _GENERATEVIVOXTOKENREQUEST._serialized_options = b'\222A\024\n\022\322\001\004type\322\001\010username'
  _SERVICE.methods_by_name['GenerateVivoxToken']._options = None
  _SERVICE.methods_by_name['GenerateVivoxToken']._serialized_options = b'\202\323\344\223\002\016\"\t/v1/token:\001*\222A$\022\024Generate Vivox tokenb\014\n\n\n\006Bearer\022\000'
  _GENERATEVIVOXTOKENREQUESTTYPE._serialized_start=544
  _GENERATEVIVOXTOKENREQUESTTYPE._serialized_end=666
  _GENERATEVIVOXTOKENREQUESTCHANNELTYPE._serialized_start=669
  _GENERATEVIVOXTOKENREQUESTCHANNELTYPE._serialized_end=803
  _GENERATEVIVOXTOKENREQUEST._serialized_start=123
  _GENERATEVIVOXTOKENREQUEST._serialized_end=478
  _GENERATEVIVOXTOKENRESPONSE._serialized_start=480
  _GENERATEVIVOXTOKENRESPONSE._serialized_end=542
  _SERVICE._serialized_start=806
  _SERVICE._serialized_end=972
# @@protoc_insertion_point(module_scope)
